### ISSUE TITLE
Lockfile issue

### ISSUE THREAD

**Issue by kelek-** [sametmax/0bin#104]
When trying to create a paste, following error comes up: 

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/home/zerobin/0bin/zerobin/routes.py", line 86, in create_paste
    paste.increment_counter()
  File "/home/zerobin/0bin/zerobin/paste.py", line 128, in increment_counter
    lock = lockfile.LockFile(counter_file)
AttributeError: 'module' object has no attribute 'LockFile'

I saw, that #94 is adressing the same issue, but it seems that it is not fixed yet.

EDIT:
OS information:
3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux
Python 2.7.9 (default, Mar  1 2015, 12:57:24)

**Comment by sametmax** [comment]
Let's +1 the previous bug report.
